server.port=8092
server.servlet.context-path=/promotion

spring.application.name=promotion
spring.threads.virtual.enabled=true
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://identity/realms/hoangtien2k3}

ecommerce.services.product=${PRODUCT_SERVICE_URL:http://api.hoangtien2k3.local/product}


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE_PROMOTION:promotion}?options=-c%20TimeZone=UTC
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Hibernate ddl auto (none, create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = none

#Enable liquibase
spring.liquibase.enabled=true

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui
springdoc.packagesToScan=com.hoangtien2k3.promotion
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.oauthflow.authorization-url=${KEYCLOAK_AUTHORIZATION_URL:http://identity/realms/hoangtien2k3/protocol/openid-connect/auth}
springdoc.oauthflow.token-url=${KEYCLOAK_TOKEN_URL:http://identity/realms/hoangtien2k3/protocol/openid-connect/token}
