elasticsearch.url=${ELASTICSEARCH_URL:localhost:9200}
elasticsearch.username=${ELASTICSEARCH_USERNAME:}
elasticsearch.password=${ELASTICSEARCH_PASSWORD:}

server.port=8092
server.servlet.context-path=/search

spring.application.name=search
spring.threads.virtual.enabled=true
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://identity/realms/hoangtien2k3}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui
springdoc.packagesToScan=com.hoangtien2k3.search
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.oauthflow.authorization-url=${KEYCLOAK_AUTHORIZATION_URL:http://identity/realms/hoangtien2k3/protocol/openid-connect/auth}
springdoc.oauthflow.token-url=${KEYCLOAK_TOKEN_URL:http://identity/realms/hoangtien2k3/protocol/openid-connect/token}

ecommerce.services.product=${PRODUCT_SERVICE_URL:http://api.hoangtien2k3.local/product}
spring.kafka.consumer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=search
product.topic.name=dbproduct.public.product

