CREATE DATABASE IF NOT EXISTS orderservice;
CREATE DATABASE IF NOT EXISTS productservice;
CREATE DATABASE IF NOT EXISTS paymentservice;
CREATE DATABASE IF NOT EXISTS userservice;
CREATE DATABASE IF NOT EXISTS inventoryservice;
CREATE DATABASE IF NOT EXISTS shippingservice;
CREATE DATABASE IF NOT EXISTS favouriteservice;
